### ISSUE TITLE
[Bug] The program fails to start up properly.

### ISSUE THREAD

**Issue by NOBTG** [ABSK495/Genshin_Paimon_Assistant#5]
![螢幕擷取畫面 2024-03-30 121243](https://github.com/ABSK495/Genshin_Paimon_Assistant/assets/139665972/24f3ce8b-9d72-47c8-ac87-7e83c5bcf4e2)

![螢幕擷取畫面 2024-03-30 121316](https://github.com/ABSK495/Genshin_Paimon_Assistant/assets/139665972/89d935af-11e8-46cf-83f1-6fa08c802d7d)

![螢幕擷取畫面 2024-03-30 121329](https://github.com/ABSK495/Genshin_Paimon_Assistant/assets/139665972/9698a28c-4316-44b5-9f3d-4a24570a4868)

![螢幕擷取畫面 2024-03-30 121345](https://github.com/ABSK495/Genshin_Paimon_Assistant/assets/139665972/45e79b53-aae9-48ba-89c3-8d8eba1821d2)

Traceback (most recent call last):
  File "configparser.py", line 767, in get
  File "collections\__init__.py", line 1014, in __getitem__
  File "collections\__init__.py", line 1006, in __missing__
KeyError: 'currentuser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "paimon.py", line 3303, in <module>
  File "paimon.py", line 2595, in read_ini_file
  File "configparser.py", line 770, in get
configparser.NoOptionError: No option 'currentuser' in section: 'User'

**Comment by ABSK495** [comment]
下载最新的0.1.7版本
Download the latest version 0.1.7

**Comment by NOBTG** [comment]
![螢幕擷取畫面 2024-04-05 212813](https://github.com/ABSK495/Genshin_Paimon_Assistant/assets/139665972/78400122-7be2-40ee-9be1-5210ce63dd19)
問題依然。

**Comment by NOBTG** [comment]
Traceback (most recent call last):
  File "configparser.py", line 767, in get
  File "collections\__init__.py", line 1014, in __getitem__
  File "collections\__init__.py", line 1006, in __missing__
KeyError: 'currentuser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "paimon.py", line 3417, in <module>
  File "paimon.py", line 2657, in read_ini_file
  File "configparser.py", line 770, in get
configparser.NoOptionError: No option 'currentuser' in section: 'User'

**Comment by ABSK495** [comment]
![image](https://github.com/ABSK495/Genshin_Paimon_Assistant/assets/61885338/7b112cf1-e225-490f-9acf-9e6a138a89fc)
定位到C:\Users\%USERNAME%\AppData\Local\paimon\地址，该目录下应该存在一个config.ini的文件，尝试删除它后重新启动软件。如果问题仍然存在，尝试手动在config.ini文件中[User]区域添加currentuser = 项并保存，使得它看起来和上图一样。

**Comment by NOBTG** [comment]
謝謝，成功了。

**Comment by NOBTG** [comment]
待我確認功能皆正常後，我將關閉此討論串。
